module risc_processor #(parameter LEGACY_DATA_MAP = 0) (
    input  wire        clk,
    input  wire        rst,
    input  wire        irq_software,
    input  wire        irq_timer,
    input  wire        irq_external,
    output wire [31:0] pc_out,
    output wire [31:0] instruction_out,
    output wire [31:0] alu_result_out,
    output wire [31:0] mem_read_data_out,
    output wire [31:0] led_out,

    output wire        retire_valid,
    output wire [31:0] retire_pc,
    output wire [31:0] retire_instruction,

    output wire        retire_rd_we,
    output wire [4:0]  retire_rd_addr,
    output wire [31:0] retire_rd_data,

    output wire        retire_mem_valid,
    output wire        retire_mem_write,
    output wire [31:0] retire_mem_addr,
    output wire [31:0] retire_mem_wdata,
    output wire [3:0]  retire_mem_wstrb,

    output wire        trap_valid,
    output wire [31:0] trap_pc,
    output wire [31:0] trap_instruction,
    output wire [31:0] trap_cause,
    output wire [31:0] trap_tval
);
    simple_soc #(.LEGACY_DATA_MAP(LEGACY_DATA_MAP)) soc (
        .clk(clk),
        .rst(rst),
        .irq_software(irq_software),
        .irq_timer(irq_timer),
        .irq_external(irq_external),
        .pc_out(pc_out),
        .instruction_out(instruction_out),
        .alu_result_out(alu_result_out),
        .mem_read_data_out(mem_read_data_out),
        .led_out(led_out),
        .retire_valid(retire_valid),
        .retire_pc(retire_pc),
        .retire_instruction(retire_instruction),
        .retire_rd_we(retire_rd_we),
        .retire_rd_addr(retire_rd_addr),
        .retire_rd_data(retire_rd_data),
        .retire_mem_valid(retire_mem_valid),
        .retire_mem_write(retire_mem_write),
        .retire_mem_addr(retire_mem_addr),
        .retire_mem_wdata(retire_mem_wdata),
        .retire_mem_wstrb(retire_mem_wstrb),
        .trap_valid(trap_valid),
        .trap_pc(trap_pc),
        .trap_instruction(trap_instruction),
        .trap_cause(trap_cause),
        .trap_tval(trap_tval)
    );
endmodule
